package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWhitelistAllows(t *testing.T) {
	home := "/home/mino/.mino"
	w := DefaultWhitelist(home)
	cases := []struct {
		name string
		argv []string
		want bool
	}{
		{"apt install exact", []string{"/usr/bin/apt-get", "install", "-y"}, true},
		{"apt install with package", []string{"/usr/bin/apt-get", "install", "-y", "jq"}, true},
		{"apt remove whitelisted", []string{"/usr/bin/apt-get", "remove", "-y", "jq"}, true},
		{"apt install missing -y", []string{"/usr/bin/apt-get", "install", "jq"}, false},
		{"apt purge refused", []string{"/usr/bin/apt-get", "purge", "-y", "jq"}, false},
		{"apt update refused", []string{"/usr/bin/apt-get", "update"}, false},
		{"systemctl restart", []string{"/usr/bin/systemctl", "restart", "mino.service"}, true},
		{"systemctl stop refused", []string{"/usr/bin/systemctl", "stop", "mino.service"}, false},
		{"daemon-reload", []string{"/usr/bin/systemctl", "daemon-reload"}, true},
		{"install unit in whitelisted dirs", []string{"/usr/bin/install", "-o", "root", "-g", "root", "-m", "0644", home + "/tmp/mino.service", "/etc/systemd/system/mino.service"}, true},
		{"install source outside tmp refused", []string{"/usr/bin/install", "-o", "root", "-g", "root", "-m", "0644", "/tmp/evil", "/etc/systemd/system/mino.service"}, false},
		{"install target outside unit dir refused", []string{"/usr/bin/install", "-o", "root", "-g", "root", "-m", "0644", home + "/tmp/x", "/usr/local/bin/x"}, false},
		{"install wrong mode refused", []string{"/usr/bin/install", "-o", "root", "-g", "root", "-m", "0777", home + "/tmp/x", "/etc/systemd/system/x"}, false},
		{"install wrong owner refused", []string{"/usr/bin/install", "-o", "pwned", "-g", "root", "-m", "0644", home + "/tmp/x", "/etc/systemd/system/x"}, false},
		{"rm unit whitelisted", []string{"/bin/rm", "-f", "/etc/systemd/system/mino.service"}, true},
		{"rm outside unit dir refused", []string{"/bin/rm", "-f", "/etc/passwd"}, false},
		{"rm -rf refused", []string{"/bin/rm", "-rf", "/etc/systemd/system/"}, false},
		{"short argv refused", []string{"/usr/bin/apt-get"}, false},
		{"unrelated command refused", []string{"/usr/bin/chmod", "777", "/etc/passwd"}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := w.Allows(tc.argv); got != tc.want {
				t.Fatalf("Allows(%v) = %v, want %v", tc.argv, got, tc.want)
			}
		})
	}
}

// The sudoers file round-trips: what setup-privileges writes is what
// AllowSudo reads, and the same commands match both sides.
func TestWhitelistSudoersRoundTrip(t *testing.T) {
	home := "/home/mino/.mino"
	w := DefaultWhitelist(home)
	lines := w.SudoersLines("mino")
	if len(lines) != 6 {
		t.Fatalf("expected 6 canonical entries, got %d: %v", len(lines), lines)
	}
	path := filepath.Join(t.TempDir(), "mino")
	content := "# generated by mino setup-privileges — do not edit\n\n" + strings.Join(lines, "\n") + "\n"
	content += "root ALL=(ALL:ALL) ALL\n" // a foreign line must be ignored
	if err := os.WriteFile(path, []byte(content), 0444); err != nil {
		t.Fatal(err)
	}
	loaded, err := LoadWhitelist(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, argv := range [][]string{
		{"/usr/bin/apt-get", "install", "-y", "jq"},
		{"/usr/bin/systemctl", "restart", "mino.service"},
		{"/usr/bin/install", "-o", "root", "-g", "root", "-m", "0644", home + "/tmp/mino.service", "/etc/systemd/system/mino.service"},
		{"/bin/rm", "-f", "/etc/systemd/system/mino.service"},
	} {
		if !loaded.Allows(argv) {
			t.Fatalf("round-tripped whitelist refuses %v", argv)
		}
	}
	if loaded.Allows([]string{"/usr/bin/apt-get", "purge", "-y", "jq"}) {
		t.Fatal("round-tripped whitelist must refuse apt-get purge")
	}
	if loaded.Allows([]string{"/usr/bin/install", "-o", "root", "-g", "root", "-m", "0644", "/tmp/x", "/etc/systemd/system/x"}) {
		t.Fatal("round-tripped whitelist must refuse a source outside the staged dir")
	}
}

func TestLoadWhitelistUnreadable(t *testing.T) {
	if _, err := LoadWhitelist(filepath.Join(t.TempDir(), "nope")); err == nil {
		t.Fatal("expected an error for a missing whitelist file")
	}
}

func TestContainsSudoInvocation(t *testing.T) {
	cases := []struct {
		cmd  string
		want bool
	}{
		{"sudo apt-get install x", true},
		{"sudo", true},
		{"x && sudo y", true},
		{"x; sudo y", true},
		{"(sudo y)", true},
		{"ls", false},
		{"apt-get install x", false},
		{"echo sudo is fine", true}, // conservative false positive — a harmless refusal
	}
	for _, tc := range cases {
		if got := containsSudoInvocation(tc.cmd); got != tc.want {
			t.Fatalf("containsSudoInvocation(%q) = %v, want %v", tc.cmd, got, tc.want)
		}
	}
}

func TestParseUnitShow(t *testing.T) {
	id, state := parseUnitShow("Id=mino.service\nUnitFileState=enabled\nActiveState=active\n")
	if id != "mino.service" || state != "enabled" {
		t.Fatalf("parseUnitShow = (%q, %q)", id, state)
	}
	if id, _ := parseUnitShow("ActiveState=active\n"); id != "" {
		t.Fatal("parseUnitShow must not invent an Id")
	}
}
