package main

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"sync"
	"testing"
	"time"
)

func TestParseORImage(t *testing.T) {
	png := []byte{0x89, 0x50, 0x4e, 0x47}
	b64 := base64.StdEncoding.EncodeToString(png)
	cases := []struct {
		name    string
		body    string
		wantErr bool
		wantExt string
	}{
		{"data-uri image_url decodes", `{"choices":[{"message":{"content":[{"type":"image_url","image_url":{"url":"data:image/png;base64,` + b64 + `"}}]}}]}`, false, ".png"},
		{"jpeg mime maps to .jpg", `{"choices":[{"message":{"content":[{"type":"image_url","image_url":{"url":"data:image/jpeg;base64,` + b64 + `"}}]}}]}`, false, ".jpg"},
		{"b64_json decodes", `{"choices":[{"message":{"content":[{"type":"image_url","b64_json":"` + b64 + `"}]}}]}`, false, ".png"},
		{"message.images array decodes", `{"choices":[{"message":{"images":[{"type":"image_url","image_url":{"url":"data:image/jpeg;base64,` + b64 + `"}}]}}]}`, false, ".jpg"},
		{"text-only content errors", `{"choices":[{"message":{"content":"sorry, no image"}}]}`, true, ""},
		{"bad json errors", `not json`, true, ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			img, ext, err := parseORImage([]byte(c.body))
			if c.wantErr {
				if err == nil {
					t.Fatal("expected error, got none")
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if !bytes.Equal(img, png) {
				t.Fatalf("decoded %v, want %v", img, png)
			}
			if ext != c.wantExt {
				t.Fatalf("ext %q, want %q", ext, c.wantExt)
			}
		})
	}
}

func TestFetchImage(t *testing.T) {
	png := []byte{0x89, 0x50, 0x4e, 0x47}
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "image/png")
		w.Write(png)
	}))
	defer srv.Close()
	img, ext, err := fetchImage(srv.URL + "/img")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !bytes.Equal(img, png) {
		t.Fatalf("decoded %v, want %v", img, png)
	}
	if ext != ".png" {
		t.Fatalf("ext %q, want .png", ext)
	}
}

func TestParseCFImage(t *testing.T) {
	png := []byte{0x89, 0x50, 0x4e, 0x47} // fake image bytes
	b64 := base64.StdEncoding.EncodeToString(png)
	cases := []struct {
		name    string
		body    string
		wantErr bool
	}{
		{"valid image decodes", `{"success":true,"result":{"image":"` + b64 + `"}}`, false},
		{"valid images array decodes", `{"success":true,"result":{"images":["` + b64 + `"]}}`, false},
		{"success false errors", `{"success":false,"result":{}}`, true},
		{"empty image errors", `{"success":true,"result":{"image":""}}`, true},
		{"bad json errors", `not json`, true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			img, err := parseCFImage([]byte(c.body))
			if c.wantErr {
				if err == nil {
					t.Fatal("expected error, got none")
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if !bytes.Equal(img, png) {
				t.Fatalf("decoded %v, want %v", img, png)
			}
		})
	}
}

// OBS-002: Only-derived (playbook stage) registries must inherit the audit
// plumbing — a fresh registry with nil auditFile/logDB made every tool call
// inside a stage invisible to audit.jsonl (live evidence 2026-08-15: 61
// images generated by scheduled runs, 0 audit entries).
func TestOnlyRegistryInheritsAuditLog(t *testing.T) {
	dir := t.TempDir()
	auditPath := filepath.Join(dir, "audit.jsonl")
	r := NewRegistry()
	if err := r.SetAuditLog(auditPath); err != nil {
		t.Fatal(err)
	}
	r.Register(behaves(&Tool{Name: "ping", Fn: func(args map[string]any) string { return "pong" }}, BehaviorObserve))

	stage := r.Only("ping")
	ctx := context.WithValue(context.Background(), sessionIDKey{}, "scheduled-test-playbook")
	if out := stage.ExecuteContext(ctx, "ping", map[string]any{}); out != "pong" {
		t.Fatalf("execute = %q", out)
	}
	r.CloseAuditLog()

	data, err := os.ReadFile(auditPath)
	if err != nil {
		t.Fatal(err)
	}
	s := string(data)
	if !strings.Contains(s, `"tool_name":"ping"`) || !strings.Contains(s, "scheduled-test-playbook") {
		t.Fatalf("stage tool call missing from audit log:\n%s", s)
	}
}

// Cloudflare image models disagree on request encoding: the FLUX.2 klein
// family requires multipart form, legacy models (flux-1-schnell) require a
// plain JSON body. generateWithCloudflare must serve both — multipart first,
// JSON retry only on a body-format rejection (the 400 is free: no generation
// happens, so the fallback costs a round-trip, not neuron budget).
func TestGenerateWithCloudflareServesBothEncodings(t *testing.T) {
	png := []byte{0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a}
	envelope := `{"success":true,"result":{"image":"` + base64.StdEncoding.EncodeToString(png) + `"}}`

	t.Setenv("CLOUDFLARE_API_TOKEN", "test-token")
	t.Setenv("CLOUDFLARE_ACCOUNT_ID", "test-account")
	t.Setenv("MINO_IMAGE_MODEL", "@cf/black-forest-labs/flux-2-klein-4b")

	oldClient, oldBase := imageClient, cfBaseURL
	defer func() { imageClient, cfBaseURL = oldClient, oldBase }()

	t.Run("multipart model succeeds first try", func(t *testing.T) {
		var cts []string
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			cts = append(cts, r.Header.Get("Content-Type"))
			w.Header().Set("Content-Type", "application/json")
			fmt.Fprint(w, envelope)
		}))
		defer ts.Close()
		imageClient, cfBaseURL = ts.Client(), ts.URL

		out, err := generateWithCloudflare(t.TempDir(), "a sunset")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(out, "via Cloudflare Workers AI") {
			t.Fatalf("output missing provenance: %q", out)
		}
		if len(cts) != 1 {
			t.Fatalf("expected exactly 1 request, got %d", len(cts))
		}
		if !strings.HasPrefix(cts[0], "multipart/form-data") {
			t.Fatalf("expected multipart content-type, got %q", cts[0])
		}
	})

	t.Run("legacy JSON model retries after multipart rejection", func(t *testing.T) {
		var cts []string
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ct := r.Header.Get("Content-Type")
			cts = append(cts, ct)
			if strings.HasPrefix(ct, "multipart/") {
				// Legacy models reject multipart bodies.
				http.Error(w, `{"errors":[{"message":"Request body is not valid json","code":6003}]}`, 400)
				return
			}
			w.Header().Set("Content-Type", "application/json")
			fmt.Fprint(w, envelope)
		}))
		defer ts.Close()
		imageClient, cfBaseURL = ts.Client(), ts.URL

		out, err := generateWithCloudflare(t.TempDir(), "a sunset")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !strings.Contains(out, "via Cloudflare Workers AI") {
			t.Fatalf("output missing provenance: %q", out)
		}
		if len(cts) != 2 {
			t.Fatalf("expected 2 requests (multipart then JSON), got %d", len(cts))
		}
		if !strings.HasPrefix(cts[1], "application/json") {
			t.Fatalf("expected JSON retry, got %q", cts[1])
		}
	})

	t.Run("non-body errors do not trigger retry", func(t *testing.T) {
		var calls int
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			calls++
			// NSFW rejection is a content error, not a body-format error.
			http.Error(w, `{"errors":[{"message":"AiError: Input prompt contains NSFW content.","code":3030}]}`, 400)
		}))
		defer ts.Close()
		imageClient, cfBaseURL = ts.Client(), ts.URL

		if _, err := generateWithCloudflare(t.TempDir(), "a sunset"); err == nil {
			t.Fatal("expected error for NSFW rejection")
		}
		if calls != 1 {
			t.Fatalf("expected single request for non-body error, got %d", calls)
		}
	})
}

// Issue #16: a non-zero exit with stdout is a PARTIAL failure — the output
// often contains the answer (find exits 1 on unreadable dirs while still
// printing matches). Agents must see the output first, not "Error: exit 1".
func TestBashPartialFailureCarriesOutput(t *testing.T) {
	tool := makeBashToolFor("", 2*time.Minute)
	out := tool.Fn(map[string]any{"command": "echo /home/mino/.mino/mino.db; exit 1"})
	if !strings.Contains(out, "PARTIAL: command exited with error") {
		t.Fatalf("partial-failure marker missing: %q", out)
	}
	if !strings.Contains(out, "/home/mino/.mino/mino.db") {
		t.Fatalf("output not carried in result: %q", out)
	}
}

// MEM-07: save_note accepts the user's verbatim words as an optional why seed,
// stored on the fact and echoed back; the seed feeds the MEM-02 judgment pass.
func TestSaveNoteCapturesWhy(t *testing.T) {
	home := t.TempDir()
	memories := filepath.Join(home, "memories")
	mem := &Memory{db: Connect(home), cfg: &Settings{Home: home, MemoriesDir: memories}, graph: NewGraphMemory(memories, nil)}
	defer mem.db.Close()
	tool := makeNotesTool(mem.db, mem)

	out := tool.Fn(map[string]any{
		"id":      "planet",
		"subject": "My planet is Mars",
		"content": "Red planet.",
		"why":     "because I live there",
	})
	if !strings.Contains(out, "why: because I live there") {
		t.Fatalf("why not echoed in result: %q", out)
	}
	fact, ok := mem.graph.FindFact("planet")
	if !ok {
		t.Fatal("fact not saved")
	}
	if fact.Why != "because I live there" {
		t.Fatalf("fact.Why = %q, want the user's verbatim words", fact.Why)
	}
	raw, err := os.ReadFile(filepath.Join(memories, "planet.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), "why: because I live there") {
		t.Fatalf("why missing from front matter:\n%s", raw)
	}
}

// MEM-07: no why given -> fact saved with empty why (never invented).
func TestSaveNoteWithoutWhy(t *testing.T) {
	home := t.TempDir()
	memories := filepath.Join(home, "memories")
	mem := &Memory{db: Connect(home), cfg: &Settings{Home: home, MemoriesDir: memories}, graph: NewGraphMemory(memories, nil)}
	defer mem.db.Close()
	tool := makeNotesTool(mem.db, mem)

	out := tool.Fn(map[string]any{"id": "plain", "subject": "Plain fact"})
	if strings.Contains(out, "why:") {
		t.Fatalf("invented a why: %q", out)
	}
	fact, ok := mem.graph.FindFact("plain")
	if !ok {
		t.Fatal("fact not saved")
	}
	if fact.Why != "" {
		t.Fatalf("fact.Why = %q, want empty (no asking, no invention)", fact.Why)
	}
}

// issue #178: save_note facts are stamped Source: "user" at birth so
// user-authored facts stay distinguishable from model-distilled ones.
func TestSaveNoteStampsUserSource(t *testing.T) {
	home := t.TempDir()
	memories := filepath.Join(home, "memories")
	mem := &Memory{db: Connect(home), cfg: &Settings{Home: home, MemoriesDir: memories}, graph: NewGraphMemory(memories, nil)}
	defer mem.db.Close()
	tool := makeNotesTool(mem.db, mem)

	if out := tool.Fn(map[string]any{"id": "user_fact", "subject": "User said this"}); !strings.Contains(out, "Saved") {
		t.Fatalf("save failed: %q", out)
	}
	fact, ok := mem.graph.FindFact("user_fact")
	if !ok {
		t.Fatal("fact not saved")
	}
	if fact.Source != "user" {
		t.Fatalf("fact.Source = %q, want \"user\"", fact.Source)
	}
	raw, err := os.ReadFile(filepath.Join(memories, "user_fact.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(raw), "source: user") {
		t.Fatalf("source missing from front matter:\n%s", raw)
	}
}

func TestBashHardFailureNoOutput(t *testing.T) {
	tool := makeBashToolFor("", 2*time.Minute)
	out := tool.Fn(map[string]any{"command": "exit 3"})
	if !strings.Contains(out, "Command failed:") || !strings.Contains(out, "no output") {
		t.Fatalf("hard-failure format wrong: %q", out)
	}
}

func TestCompactSchemaStripsProseKeepsStructure(t *testing.T) {
	schema := map[string]any{
		"type":        "object",
		"description": "top prose",
		"properties": map[string]any{
			"slug": map[string]any{"type": "string", "description": "tool slug", "pattern": "^[A-Z_]+$"},
			"nested": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"flag": map[string]any{"type": "boolean", "default": false, "examples": []any{true}},
				},
				"required": []any{"flag"},
			},
		},
		"required": []any{"slug"},
	}
	got := compactSchema(schema)
	if got["description"] != nil {
		t.Fatal("top-level description should be stripped")
	}
	props := got["properties"].(map[string]any)
	slug := props["slug"].(map[string]any)
	if slug["description"] != nil {
		t.Fatalf("property prose not stripped: %#v", slug)
	}
	if slug["type"] != "string" || slug["pattern"] != "^[A-Z_]+$" {
		t.Fatalf("property type/constraint lost: %#v", slug)
	}
	nested := props["nested"].(map[string]any)
	flag := nested["properties"].(map[string]any)["flag"].(map[string]any)
	if flag["default"] != nil || flag["examples"] != nil {
		t.Fatalf("default/examples not stripped: %#v", flag)
	}
	if flag["type"] != "boolean" {
		t.Fatalf("nested type lost: %#v", flag)
	}
	if req := nested["required"].([]any); len(req) != 1 || req[0] != "flag" {
		t.Fatalf("required lost: %#v", nested["required"])
	}
	if compactSchema(nil) != nil {
		t.Fatal("nil schema should stay nil")
	}
}

func TestToolDefCapsLongDescription(t *testing.T) {
	r := NewRegistry()
	long := strings.Repeat("d", 5000)
	r.Register(&Tool{Name: "big", Description: long, Schema: map[string]any{"type": "object"}})
	def := r.toolDef(r.tools["big"])
	if len(def.Description) > toolDescCap+3 {
		t.Fatalf("description = %d chars, want ≤ %d", len(def.Description), toolDescCap)
	}
	if !strings.HasSuffix(def.Description, "…") {
		t.Fatalf("missing truncation marker: %.20q", def.Description)
	}
	// Short descriptions pass through untouched.
	short := "pong"
	r.Register(&Tool{Name: "small", Description: short, Schema: map[string]any{"type": "object"}})
	if def := r.toolDef(r.tools["small"]); def.Description != short {
		t.Fatalf("short description altered: %q", def.Description)
	}
	// Operator override via MINO_MAX_TOOL_DESC_CHARS.
	r.SetMaxToolDescChars(200)
	if def := r.toolDef(r.tools["big"]); len(def.Description) > 203 {
		t.Fatalf("override not honored: %d chars", len(def.Description))
	}
}

func unionNames(u *schemaUnion) []string {
	return append([]string(nil), u.order...)
}

func TestSchemaUnionCapEvictsLRU(t *testing.T) {
	u := newSchemaUnion()
	for _, n := range []string{"a", "b", "c", "d", "e"} {
		u.selectName(n)
	}
	u.capAt(3, nil, nil)
	if got, want := unionNames(u), []string{"c", "d", "e"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("after cap 3: %v, want %v", got, want)
	}
}

func TestSchemaUnionRefreshKeepsRecent(t *testing.T) {
	u := newSchemaUnion()
	for _, n := range []string{"a", "b", "c"} {
		u.selectName(n)
	}
	u.selectName("a") // refresh: a is now most recent
	u.capAt(2, nil, nil)
	if got, want := unionNames(u), []string{"c", "a"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("after refresh+cap: %v, want %v", got, want)
	}
}

func TestSchemaUnionPinnedNeverEvicted(t *testing.T) {
	u := newSchemaUnion()
	for _, n := range []string{"a", "b", "c", "d"} {
		u.selectName(n)
	}
	u.capAt(2, map[string]bool{"b": true}, nil)
	if got, want := unionNames(u), []string{"b", "d"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("pinned b evicted or wrong survivors: %v, want %v", got, want)
	}
}

func TestSchemaUnionExplicitImmunity(t *testing.T) {
	u := newSchemaUnion()
	for _, n := range []string{"a", "b", "c", "d"} {
		u.selectName(n)
	}
	// a is oldest but explicitly named this turn → survives; b, c go.
	u.capAt(2, nil, map[string]bool{"a": true})
	if got, want := unionNames(u), []string{"a", "d"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("immune a evicted: %v, want %v", got, want)
	}
}

func TestSchemaUnionImmuneOverflowStays(t *testing.T) {
	// pinned+immune > cap: protected tools survive, union stays larger.
	u := newSchemaUnion()
	for _, n := range []string{"a", "b", "c", "d"} {
		u.selectName(n)
	}
	u.capAt(2, map[string]bool{"a": true, "b": true}, map[string]bool{"c": true, "d": true})
	if got, want := unionNames(u), []string{"a", "b", "c", "d"}; !reflect.DeepEqual(got, want) {
		t.Fatalf("protected tools dropped: %v, want %v", got, want)
	}
}

// TestSchemasForContextCappedUnion exercises the union through the real
// selection path: essentials always present, cap 20 enforced, oldest explicit
// tools evicted when new ones arrive, and the output byte-stable across
// identical turns (prefix-cache requirement).
func TestSchemasForContextCappedUnion(t *testing.T) {
	db, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if _, err := db.Exec("CREATE VIRTUAL TABLE tool_catalog_fts USING fts5(name, description, keywords)"); err != nil {
		t.Fatal(err)
	}
	r := NewRegistry()
	for _, name := range essentialNamesSorted {
		r.Register(&Tool{Name: name, Description: "essential", Schema: map[string]any{"type": "object"}})
	}
	for i := 100; i < 130; i++ {
		r.Register(&Tool{Name: fmt.Sprintf("special_%d", i), Description: "specialized tool", Schema: map[string]any{"type": "object"}})
	}
	r.SetSearchDB(db)

	names := func(schemas []ToolDef) []string {
		out := make([]string, len(schemas))
		for i, s := range schemas {
			out[i] = s.Name
		}
		return out
	}
	hasAll := func(t *testing.T, got []string, want ...string) {
		t.Helper()
		for _, w := range want {
			found := false
			for _, g := range got {
				if g == w {
					found = true
					break
				}
			}
			if !found {
				t.Fatalf("missing %q in %v", w, got)
			}
		}
	}

	// Turn 1: 13 essentials (send_document added, CTX-013) + 6 explicit = 19, under the cap.
	first := names(r.SchemasForContext("s1", "", "use special_101 special_102 special_103 special_104 special_105 special_106 now"))
	if len(first) != 19 {
		t.Fatalf("turn 1: %d schemas, want 19: %v", len(first), first)
	}
	hasAll(t, first, essentialNamesSorted...)

	// Turn 2: 6 new explicit tools → union 23 → evict the 3 oldest explicit.
	second := names(r.SchemasForContext("s1", "", "use special_107 special_108 special_109 special_110 special_111 special_112 now"))
	if len(second) != schemaUnionCap {
		t.Fatalf("turn 2: %d schemas, want cap %d", len(second), schemaUnionCap)
	}
	hasAll(t, second, essentialNamesSorted...)
	hasAll(t, second, "special_106", "special_107", "special_108", "special_109", "special_110", "special_111", "special_112")
	for _, gone := range []string{"special_101", "special_102", "special_103", "special_104", "special_105"} {
		for _, g := range second {
			if g == gone {
				t.Fatalf("%s survived eviction: %v", gone, second)
			}
		}
	}

	// Turn 3: identical to turn 2 → identical output (prefix-cache stability).
	third := names(r.SchemasForContext("s1", "", "use special_107 special_108 special_109 special_110 special_111 special_112 now"))
	if !reflect.DeepEqual(second, third) {
		t.Fatalf("unstable output across identical turns:\n%v\n%v", second, third)
	}

	// A different session starts its own union.
	other := names(r.SchemasForContext("s2", "", "use special_107 special_108 special_109 special_110 special_111 special_112 now"))
	if len(other) != 19 {
		t.Fatalf("session s2 inherited union: %d schemas, want 19", len(other))
	}
}

// The bash tool rewrites commands through rtk when present (token-lean
// output). The rewrite is trusted by OUTPUT SHAPE, not exit code: rtk 0.43.0
// exits 3 (not the documented 0) for valid rewrites, so an exit-code check
// would disable the feature; but usage text from an older rtk without the
// rewrite subcommand must never replace the command.
func TestRewriteBashWithRTK(t *testing.T) {
	stubDir := filepath.Join(t.TempDir(), "bin")
	os.MkdirAll(stubDir, 0755)
	stub := filepath.Join(stubDir, "rtk")
	// The stub echoes RTK_STUB_RESPONSE and exits with RTK_STUB_CODE.
	os.WriteFile(stub, []byte("#!/bin/sh\nprintf '%s' \"$RTK_STUB_RESPONSE\"\nexit \"${RTK_STUB_CODE:-0}\"\n"), 0755)

	cases := []struct {
		name     string
		hasRTK   bool
		response string
		code     string
		want     string
	}{
		{"valid rewrite, quirky exit 3", true, "rtk ls -la /tmp", "3", "rtk ls -la /tmp"},
		{"compound rewrite", true, "cd /tmp && rtk ls", "3", "cd /tmp && rtk ls"},
		{"no equivalent -> empty output", true, "", "1", "ls -la /tmp"},
		{"old rtk usage dump on stdout", true, "A high-performance CLI proxy...\nUsage: rtk [OPTIONS] <COMMAND>", "1", "ls -la /tmp"},
		{"multiline noise", true, "rtk ls -la /tmp\nrtk git log", "3", "ls -la /tmp"},
		{"rtk not installed", false, "", "0", "ls -la /tmp"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			bin := stubDir
			if !tc.hasRTK {
				bin = filepath.Join(t.TempDir(), "nobin")
				os.MkdirAll(bin, 0755)
			}
			t.Setenv("PATH", bin)
			t.Setenv("RTK_STUB_RESPONSE", tc.response)
			t.Setenv("RTK_STUB_CODE", tc.code)
			got := rewriteBashWithRTK(context.Background(), "ls -la /tmp")
			if got != tc.want {
				t.Fatalf("got %q, want %q", got, tc.want)
			}
		})
	}
}

// The literal-"\n" Telegram report class (2026-08-14): the model emitted
// JSON-escaped newlines in send_message args; the tool must normalize them so
// the outbox carries real line breaks.
func TestSendMessageNormalizesLiteralNewlines(t *testing.T) {
	home := t.TempDir()
	tool := makeMessagesTool(home)
	got := tool.Fn(map[string]any{"to": "abah", "message": "Line1\\n\\nLine2"})
	if !strings.Contains(got, "drafted") {
		t.Fatalf("unexpected result: %q", got)
	}
	data, err := os.ReadFile(filepath.Join(home, "outbox", "msg_abah.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != "Line1\n\nLine2" {
		t.Fatalf("outbox message = %q, want real newlines", string(data))
	}
}

// The entity-escape fallback class (2026-08-14): the plain-text fallback left
// &amp; &lt; &#8217; raw; unescape after tag stripping.
func TestFetchURLFallbackUnescapesEntities(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/html")
		fmt.Fprint(w, "<html><body><p>AT&amp;T &lt;b&gt;bold&lt;/b&gt; &#8217;quoted&#8217;</p></body></html>")
	}))
	defer srv.Close()
	got := fetchURL(srv.URL)
	for _, want := range []string{"AT&T", "<b>bold</b>", "\u2019quoted\u2019"} {
		if !strings.Contains(got, want) {
			t.Fatalf("fallback output missing %q: %q", want, got)
		}
	}
	if strings.Contains(got, "&amp;") {
		t.Fatalf("raw entity survived: %q", got)
	}
}

// DRF-002 provenance honesty: save_note stamps model-distill inside a playbook
// run (the save is Mino's own learning) and user outside one.
func TestSaveNoteStampsModelDistillInsidePlaybook(t *testing.T) {
	home := t.TempDir()
	gm := NewGraphMemory(filepath.Join(home, "memories"), &Settings{TopK: 2})
	mem := &Memory{graph: gm}
	tool := makeNotesTool(nil, mem)

	// Outside a playbook: user stamp.
	tool.Fn(map[string]any{"id": "outside_playbook", "subject": "user note outside playbook"})
	if f := gm.facts["outside_playbook"]; f == nil || f.Source != "user" {
		t.Fatalf("outside playbook source = %v, want user", f)
	}

	// Inside a playbook run: model-distill stamp.
	playbookDepth.Add(1)
	defer playbookDepth.Add(-1)
	tool.Fn(map[string]any{"id": "inside_playbook", "subject": "concept learned during playbook run"})
	if f := gm.facts["inside_playbook"]; f == nil || f.Source != "model-distill" {
		t.Fatalf("inside playbook source = %v, want model-distill", f)
	}
}

// DRF-002: stale_after round-trips through the front-matter.
func TestStaleAfterRoundTrip(t *testing.T) {
	gm := NewGraphMemory(t.TempDir(), &Settings{TopK: 2})
	future := time.Now().Add(30 * 24 * time.Hour)
	mustRecord(t, gm, Fact{ID: "volatile", Type: "semantic", Subject: "current model stack", StaleAfter: future, Source: "graph-rebuild", At: time.Now()})
	// Re-read from disk: Refresh + fact lookup must carry stale_after.
	gm.Refresh()
	f, ok := gm.facts["volatile"]
	if !ok {
		t.Fatal("fact missing after refresh")
	}
	if f.StaleAfter.IsZero() {
		t.Fatal("stale_after lost in round-trip")
	}
	if d := future.Sub(f.StaleAfter); d < 0 || d > time.Minute {
		t.Fatalf("stale_after drifted in round-trip: %v vs %v", f.StaleAfter, future)
	}
}

// CTX-022 C (proactive): search_web consults the graph itself — a
// user-provenanced fact on the query topic is named before the external
// content, even when the model never called remember first (observed
// 2026-08-15 live: the Agent-Reach question went straight to web and
// repeated the wrong answer; the reactive loop gate never fired).
func TestSearchToolProactiveProvenanceGate(t *testing.T) {
	dir := t.TempDir()
	gm := NewGraphMemory(dir, nil)
	if err := gm.RecordFact(Fact{
		ID: "repo_deleted", Type: "semantic", Source: "user",
		Subject: "The Agent-Reach repo was deleted per request",
		Why:     "so I know it is gone",
	}); err != nil {
		t.Fatal(err)
	}
	mem := &Memory{graph: gm}
	tool := makeSearchTool(mem)
	out := tool.Fn(map[string]any{"query": "Agent-Reach repo status"})
	if !strings.Contains(out, "provenance gate") || !strings.Contains(out, "repo_deleted") {
		t.Fatalf("proactive gate missing:\n%s", out)
	}
	// Non-overlapping query stays clean.
	out2 := tool.Fn(map[string]any{"query": "weather today kuala lumpur"})
	if strings.Contains(out2, "provenance gate") {
		t.Fatalf("gate fired on unrelated query:\n%s", out2)
	}
}

// F1 regression (RUN-001 review, PR #224): syncToolCatalog must not iterate
// the tools map unlocked — concurrent registration (supervisor runLoop
// goroutines) racing the FTS catalog rebuild. Fails under -race without the
// toolsMu guard inside syncToolCatalog.
func TestRegistryConcurrentRegisterCatalogRebuild(t *testing.T) {
	r := NewRegistry()
	r.SetSearchDB(Connect(t.TempDir())) // searchDB set → syncToolCatalog does real work
	var wg sync.WaitGroup
	wg.Add(2)
	go func() { // register storm — locked map writes + catalog rebuilds
		defer wg.Done()
		for i := 0; i < 20; i++ {
			r.Register(&Tool{Name: fmt.Sprintf("tool_%d", i), Description: "concurrent registration"})
		}
	}()
	go func() { // catalog rebuild + read storm — overlaps the registration writes
		defer wg.Done()
		for i := 0; i < 25; i++ {
			r.syncToolCatalog()
			r.Catalog()
			r.Schemas()
		}
	}()
	wg.Wait()
}
